---
before:
  hooks:
    - go mod tidy
builds:
  - id: harvey
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/harvey
    binary: harvey
    ldflags:
      - -s -w -X github.com/mikfreedman/harvey/main.version={{.Version}} -extldflags '-static'

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: "harvey_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-snapshot-{{.ShortCommit}}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs(\(.*\))?:'
      - '^test(\(.*\))?:'
      - '^ci(\(.*\))?:'
      - '^chore(\(.*\))?:'
      - '^build(\(.*\))?:'
project_name: harvey
dockers:
  - image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest'
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=VERSION={{.Version}}"
      - "--platform=linux/amd64"
brews:
  - name: harvey

    tap:
      owner: mikfreedman
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/mikfreedman/harvey"

    # Template of your app's description.
    # Default is empty.
    description: "Remove Extra Stuff from Markdown"

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "Apache-2.0"

    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # If set to auto, the release will not be uploaded to the homebrew tap
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Default is false.
    skip_upload: auto

    install: |-
      bin.install "harvey"
    # So you can `brew test` your formula.
    # Default is empty.
    test: |
      system "#{bin}/harvey --version"
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://github.com/mikfreedman/harvey
    description: "Build and maintain groups on the basis of reporting hierarchy."
    maintainer: Mik Freedman <github@michael-freedman.com
    license: MIT
    vendor: mikfreedman
    formats:
      - apk
      - deb
      - rpm